[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dialogue_modelling"
version = "0.1.0"
dependencies = [
]

[tool.setuptools]
packages = ["utils"]